export default {
  categories: [
    {
      name: 'Technology',
      image:
        'https://media.istockphoto.com/id/1133769508/vector/detachable-device-technology-concept-banner-header.jpg?s=170667a&w=0&k=20&c=9l-O5L_tbv1A_oTTkxOGp-JEMRAwKVTnqJniXRkCM28=',
      subcategories: [
        {
          name: 'Web Development',
          image:
            'https://www.elegantthemes.com/blog/wp-content/uploads/2018/12/top11.png',
          skills: [
            'HTML',
            'CSS',
            'JavaScript',
            'React',
            'Angular',
            'Vue.js',
            'Node.js',
            'PHP',
            'Ruby on Rails',
            'WordPress',
          ],
        },
        {
          name: 'Mobile Development',
          image:
            'https://assets-global.website-files.com/6410ebf8e483b5bb2c86eb27/6410ebf8e483b5758186fbd8_ABM%20college%20mobile%20app%20dev%20main.jpg',
          skills: [
            'Swift',
            'Java',
            'Kotlin',
            'Objective-C',
            'React Native',
            'Flutter',
            'Ionic',
            'Xamarin',
            'PhoneGap',
            'Appcelerator Titanium',
          ],
        },
        {
          name: 'Database Administration',
          image:
            'https://www.techrepublic.com/wp-content/uploads/2018/04/istock-858118324.jpg',
          skills: [
            'MySQL',
            'PostgreSQL',
            'Oracle',
            'MongoDB',
            'Microsoft SQL Server',
            'Redis',
            'Cassandra',
            'Amazon DynamoDB',
            'MariaDB',
            'Couchbase',
          ],
        },
        {
          name: 'Cloud Computing',
          image:
            'https://www.mend.io/wp-content/media/2021/06/Cloud-Security-Blog.png',
          skills: [
            'Amazon Web Services (AWS)',
            'Microsoft Azure',
            'Google Cloud Platform (GCP)',
            'IBM Cloud',
            'Oracle Cloud',
            'Alibaba Cloud',
            'Salesforce',
            'VMware',
            'OpenStack',
            'Red Hat OpenShift',
          ],
        },
        {
          name: 'Cybersecurity',
          image: 'https://www.buildingsiot.com/hubfs/cybersecurity.png',
          skills: [
            'Network Security',
            'Penetration Testing',
            'Security Information and Event Management (SIEM)',
            'Intrusion Detection and Prevention Systems (IDPS)',
            'Antivirus and Antimalware Solutions',
            'Data Encryption',
            'Identity and Access Management (IAM)',
            'Disaster Recovery and Business Continuity',
            'Cloud Security',
            'Risk Assessment and Management',
          ],
        },
        {
          name: 'Artificial Intelligence',
          image:
            'https://www.xpand-it.com/wp-content/uploads/2022/08/Artificial-intelligence_blog.png',
          skills: [
            'Machine Learning',
            'Deep Learning',
            'Natural Language Processing (NLP)',
            'Computer Vision',
            'Robotics',
            'Expert Systems',
            'Neural Networks',
            'Genetic Algorithms',
            'Fuzzy Logic',
            'Reinforcement Learning',
          ],
        },
        {
          name: 'Project Management',
          image:
            'https://project-management.com/wp-content/uploads/2017/02/pmcom-how-delegate-project-management.jpeg',
          skills: [
            'Agile Methodologies',
            'Waterfall Methodologies',
            'Scrum',
            'Kanban',
            'PMBOK',
            'PRINCE2',
            'Six Sigma',
            'Risk Management',
            'Quality Management',
            'Stakeholder Management',
          ],
        },
        {
          name: 'UI/UX Design',
          image:
            'https://leverageedublog.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2020/07/30182024/UX-UI-Design.jpg',
          skills: [
            'User Research',
            'Information Architecture',
            'Wireframing',
            'Prototyping',
            'Visual Design',
            'Interaction Design',
            'Usability Testing',
            'Accessibility',
            'Responsive Design',
            'Design Thinking',
          ],
        },
        {
          name: 'Data Science',
          image:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5Djin05IA9uykUYLU3IoyVRoB9NQ9LZJwvg&usqp=CAU',
          skills: [
            'Python',
            'R',
            'Data Mining',
            'Data Wrangling',
            'Data Visualization',
            'Statistical Analysis',
            'Machine Learning',
            'Deep Learning',
            'Big Data Technologies',
            'Cloud Computing for Data Science',
          ],
        },
        {
          name: 'DevOps',
          image:
            'https://coodesh.com/blog/wp-content/uploads/2022/03/devops-scaled.jpg',
          skills: [
            'Continuous Integration and Continuous Deployment (CI/CD)',
            'Configuration Management',
            'Infrastructure as Code (IaC)',
            'Containerization',
            'Orchestration',
            'Monitoring and Logging',
            'Version Control',
            'Collaboration and Communication Tools',
            'Agile and Lean Principles',
            'Site Reliability Engineering (SRE)',
          ],
        },
      ],
    },
    {
      name: 'Business',
      image:
        'https://cloudcfo.ph/wp-content/uploads/2022/11/CloudCfo-Blog-Banner-Blog17-Business-Structures.png',
      subcategories: [
        {
          name: 'Marketing',
          image:
            'https://builtin.com/sites/www.builtin.com/files/styles/ckeditor_optimize/public/inline-images/marketing-pillar-page-marketing-overview_0.png',
          skills: [
            'Social Media Marketing',
            'Search Engine Optimization (SEO)',
            'Search Engine Marketing (SEM)',
            'Email Marketing',
            'Content Marketing',
            'Video Marketing',
            'Influencer Marketing',
            'Affiliate Marketing',
            'Marketing Analytics',
            'Marketing Automation',
          ],
        },
        {
          name: 'Finance',
          image:
            'https://builtin.com/sites/www.builtin.com/files/styles/ckeditor_optimize/public/inline-images/marketing-pillar-page-marketing-overview_0.png',
          skills: [
            'Financial Analysis',
            'Investment Management',
            'Accounting',
            'Taxation',
            'Risk Management',
            'Corporate Finance',
            'Financial Planning and Budgeting',
            'Auditing',
            'Financial Modeling',
            'Financial Reporting',
          ],
        },
        {
          name: 'Human Resources',
          image:
            'https://eddy.com/wp-content/uploads/2021/02/why-is-human-resources-important@2x-100-1200x900.jpg',
          skills: [
            'Recruiting and Hiring',
            'Performance Management',
            'Compensation and Benefits',
            'Employee Relations',
            'Labor Laws and Regulations',
            'HR Information Systems (HRIS)',
            'Training and Development',
            'Diversity and Inclusion',
            'Succession Planning',
            'Employee Engagement',
          ],
        },
        {
          name: 'Sales',
          image:
            'https://assets-global.website-files.com/6318e6b2f58b77044875e67b/632b2eb47b58103aeac94c5f_62263643fcd1b61f8b78ab7b_sales-volume.png',
          skills: [
            'Prospecting',
            'Lead Generation',
            'Sales Negotiation',
            'Sales Presentations',
            'Account Management',
            'Sales Analytics',
            'Customer Relationship Management (CRM)',
            'Sales Operations',
            'Sales Training and Coaching',
            'Sales Strategy and Planning',
          ],
        },
        {
          name: 'Operations',
          image:
            'https://d3kqdc25i4tl0t.cloudfront.net/articles/content/515_974784_operations.hero.jpg',
          skills: [
            'Process Improvement',
            'Project Management',
            'Supply Chain Management',
            'Inventory Management',
            'Quality Management',
            'Facilities Management',
            'Logistics and Distribution',
            'Lean Manufacturing',
            'Six Sigma',
            'Capacity Planning',
          ],
        },
        {
          name: 'Entrepreneurship',
          image:
            'https://apacentrepreneur.com/wp-content/uploads/2021/03/Social-Entrepreneur.jpg',
          skills: [
            'Business Planning',
            'Market Research',
            'Financial Management',
            'Business Model Canvas',
            'Pitching and Presenting',
            'Networking',
            'Team Building and Leadership',
            'Mentorship and Coaching',
            'Innovation and Creativity',
            'Risk Management',
          ],
        },
        {
          name: 'Legal',
          image:
            'https://leverageedublog.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2020/01/27134004/Business-Law.png',
          skills: [
            'Contract Law',
            'Intellectual Property Law',
            'Employment Law',
            'Corporate Law',
            'Mergers and Acquisitions (M&A)',
            'Litigation',
            'Regulatory Compliance',
            'Data Privacy and Security',
            'International Law',
            'Arbitration and Mediation',
          ],
        },
        {
          name: 'Customer Service',
          image:
            'https://www.revechat.com/wp-content/uploads/2022/02/customer-support-2-1280x720.jpg',
          skills: [
            'Customer Satisfaction',
            'Customer Retention',
            'Complaint Resolution',
            'Effective Communication',
            'Product Knowledge',
            'Service Recovery',
            'Quality Assurance',
            'Technical Support',
            'Customer Service Metrics',
            'Customer Experience Management',
          ],
        },
        {
          name: 'Product Management',
          image:
            'https://www.seunogunmola.com.ng/wp-content/uploads/2023/02/productmanager.jpeg',
          skills: [
            'Product Strategy',
            'Product Development',
            'Market Research',
            'Product Roadmapping',
            'User-Centered Design (UCD)',
            'Agile Product Management',
            'Product Backlog Management',
            'Product Launch',
            'Product Marketing',
            'Competitive Analysis',
          ],
        },
        {
          name: 'Data Science',
          image:
            'https://www.siliconrepublic.com/wp-content/uploads/2022/02/data-science-skills.jpeg',
          skills: [
            'Statistics',
            'Machine Learning',
            'Data Visualization',
            'Data Mining',
            'Data Cleaning and Preprocessing',
            'Data Wrangling',
            'Big Data Technologies',
            'Database Management',
            'Programming Languages for Data Science',
            'Experimental Design',
          ],
        },
      ],
    },
    {
      name: 'Creative',
      image:
        'https://img.freepik.com/premium-vector/brainstorming-decision-making-idea-conceptual-illustration-with-male-character-with-thinking_148087-645.jpg',
      subcategories: [
        {
          name: 'Graphic Design',
          image:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWVYO9oarXDo4y6K_Te0qXFx6akDseNrqvO4qIHenEmJZ2YAUZpgAQVaebJXaXddEvFjs&usqp=CAU',
          skills: [
            'Adobe Photoshop',
            'Adobe Illustrator',
            'Brand Identity Design',
            'Typography',
            'Layout Design',
            'Print Design',
            'User Interface (UI) Design',
            'User Experience (UX) Design',
            'Web Design',
            'Motion Graphics',
          ],
        },
        {
          name: 'Photography',
          image:
            'https://www.legalzoom.com/sites/lz.com/files/inline-images/articles/14_things_to_include_in_your_photography_contract_1.jpg.pagespeed.ce.xRrIgI36Iv.jpg',
          skills: [
            'Camera Operation',
            'Lighting',
            'Composition',
            'Photo Editing',
            'Portrait Photography',
            'Landscape Photography',
            'Fashion Photography',
            'Product Photography',
            'Street Photography',
            'Event Photography',
          ],
        },
        {
          name: 'Video Production',
          image:
            'https://dme.studio/wp-content/uploads/2022/01/Animate-Marketing-Videos-for-Business-scaled.jpg',
          skills: [
            'Storyboarding',
            'Cinematography',
            'Scriptwriting',
            'Directing',
            'Video Editing',
            'Color Grading',
            'Sound Design',
            'Motion Graphics',
            'Visual Effects (VFX)',
            'Live Streaming',
          ],
        },
        {
          name: 'Writing',
          image:
            'https://www.science.org/do/10.1126/science.caredit.aay5007/abs/Letters_to_Young_Scientists_1280x720.jpg',
          skills: [
            'Copywriting',
            'Content Writing',
            'Journalism',
            'Technical Writing',
            'Creative Writing',
            'Editing and Proofreading',
            'Research',
            'SEO Writing',
            'Ghostwriting',
            'Grant Writing',
          ],
        },
        {
          name: 'Music',
          image:
            'https://img.freepik.com/premium-vector/music-producer-illustration-concept-white_701961-2149.jpg',
          skills: [
            'Instrument Playing',
            'Music Theory',
            'Composition and Arrangement',
            'Recording and Production',
            'Sound Design',
            'Live Performance',
            'Music Business and Marketing',
            'Music Technology',
            'Music Education',
            'Music Therapy',
          ],
        },
        {
          name: 'Fashion',
          image:
            'https://media.istockphoto.com/id/1248438483/vector/hobby-2.jpg?s=612x612&w=0&k=20&c=HGb5YG2xgxgNF3zWdeSlFYnWdw8xIN7yFx16JI77Rzs=',
          skills: [
            'Fashion Design',
            'Sewing and Patternmaking',
            'Textile Design',
            'Fashion Illustration',
            'Garment Construction',
            'Fashion Merchandising',
            'Fashion Styling',
            'Fashion Photography',
            'Fashion Business and Marketing',
            'Sustainable Fashion',
          ],
        },
        {
          name: 'Fine Arts',
          image:
            'https://leverageedublog.s3.ap-south-1.amazonaws.com/blog/wp-content/uploads/2020/07/29211327/Art-Schools-1.jpg',
          skills: [
            'Drawing',
            'Painting',
            'Sculpting',
            'Printmaking',
            'Mixed Media',
            'Performance Art',
            'Installation Art',
            'Art History',
            'Curating',
            'Art Education',
          ],
        },
        {
          name: 'Crafts',
          image:
            'https://img.freepik.com/free-vector/diy-creative-workshop-concept-with-hands-using-scissors-illustration_23-2148528369.jpg?w=360',
          skills: [
            'Knitting and Crocheting',
            'Sewing',
            'Quilting',
            'Embroidery',
            'Jewelry Making',
            'Pottery',
            'Woodworking',
            'Glassblowing',
            'Metalworking',
            'Leatherworking',
          ],
        },
        {
          name: 'Cooking',
          image:
            'https://e0.pxfuel.com/wallpapers/119/899/desktop-wallpaper-premium-vector-cartoon-cook-chef-illustration-restaurant-cook-chef-hat-and-cook-uniform-cooking-cartoon.jpg',
          skills: [
            'Recipe Development',
            'Culinary Techniques',
            'Food Photography',
            'Baking',
            'Grilling',
            'Sous Vide',
            'Slow Cooking',
            'Meal Planning',
            'Wine Pairing',
            'Food Safety and Sanitation',
          ],
        },
        {
          name: 'Performing Arts',
          image:
            'https://img.freepik.com/premium-vector/symphony-orchestra-playing-classical-music-concert_87771-7178.jpg',
          skills: [
            'Acting',
            'Dancing',
            'Singing',
            'Musical Instrument Playing',
            'Choreography',
            'Stage Direction',
            'Theater Design and Production',
            'Playwriting',
            'Improvisation',
            'Performance Critique and Analysis',
          ],
        },
      ],
    },
    {
      name: 'Language and Communication',
      image:
        'https://img.freepik.com/premium-vector/symphony-orchestra-playing-classical-music-concert_87771-7178.jpg',
      subcategories: [
        {
          name: 'Translation',
          image:
            'https://greatcontent.com/wp-content/uploads/2022/03/Translation.png',
          skills: [
            'Fluent in at least two languages',
            'Accuracy and attention to detail',
            'Cultural understanding',
            'Subject matter expertise',
            'Translation software proficiency',
            'Proofreading and editing',
            'Time management',
            'Strong communication skills',
            'Confidentiality',
            'Research and information gathering',
          ],
        },
        {
          name: 'Interpretation',
          skills: [
            'Fluent in at least two languages',
            'Active listening and comprehension',
            'Cultural understanding',
            'Subject matter expertise',
            'Consecutive and simultaneous interpretation',
            'Note-taking and memory recall',
            'Public speaking',
            'Strong communication skills',
            'Confidentiality',
            'Quick thinking and problem-solving',
          ],
        },
        {
          name: 'Writing and Editing',
          image:
            'https://thumbs.dreamstime.com/b/english-grammar-examination-concept-tiny-people-characters-correct-mistakes-errors-paper-digital-test-fail-exam-results-179187634.jpg',
          skills: [
            'Grammar and punctuation',
            'Research and fact-checking',
            'Organization and structure',
            'Audience awareness',
            'Editing and proofreading',
            'SEO writing',
            'Technical writing',
            'Creative writing',
            'Business and academic writing',
            'Collaboration and communication',
          ],
        },
        {
          name: 'Public Speaking',
          image:
            'https://ahaslides.com/wp-content/uploads/2022/08/SEO1069-thumb.png',
          skills: [
            'Message development and organization',
            'Voice and body language',
            'Audience analysis',
            'Visual aids and technology',
            'Persuasion and influence',
            'Delivery and timing',
            'Handling questions and objections',
            'Confidence and presence',
            'Adaptability and improvisation',
            'Feedback and self-reflection',
          ],
        },
        {
          name: 'Journalism',
          image:
            'https://www.rappler.com/tachyon/r3-assets/612F469A6EA84F6BAE882D2B94A4B421/img/BA497DC23F9C4D3DA0652644A150CE3F/campus-journ.jpg',
          skills: [
            'Interviewing and research',
            'News writing and reporting',
            'Investigative reporting',
            'Editing and fact-checking',
            'Media law and ethics',
            'Broadcast journalism',
            'Data journalism',
            'Social media and audience engagement',
            'Critical thinking and analysis',
            'Adaptability and resilience',
          ],
        },
        {
          name: 'Communication Strategy',
          image:
            'https://assets.entrepreneur.com/content/3x2/2000/1593528636-GettyImages-1214048312.jpg',
          skills: [
            'Branding and messaging',
            'Media relations and outreach',
            'Crisis communication',
            'Social media management',
            'Digital marketing',
            'Audience analysis and segmentation',
            'Content strategy and creation',
            'Measurement and evaluation',
            'Leadership and team management',
            'Project management',
          ],
        },
        {
          name: 'Linguistics',
          image:
            'https://languageanimated.com/wp-content/uploads/2021/10/Language-SLider.png',
          skills: [
            'Phonetics and phonology',
            'Morphology and syntax',
            'Semantics and pragmatics',
            'Language acquisition and development',
            'Psycholinguistics',
            'Sociolinguistics',
            'Historical linguistics',
            'Language teaching and learning',
            'Computational linguistics',
            'Language documentation and preservation',
          ],
        },
        {
          name: 'Teaching and Tutoring',
          image:
            'https://img.freepik.com/premium-vector/mom-does-homework-with-son-boy-is-engaged-with-tutor-woman-child-reading-book-home-schooling-school-homework-teacher-student_499739-878.jpg?w=2000',
          skills: [
            'Lesson planning and delivery',
            'Classroom management',
            'Differentiated instruction',
            'Assessment and evaluation',
            'Curriculum development',
            'Learning styles and modalities',
            'Communication and collaboration',
            'Cultural competence and diversity',
            'Technology integration',
            'Professional development and self-reflection',
          ],
        },
        {
          name: 'Foreign Languages',
          image: '',
          skills: [
            'Reading, writing, speaking, and listening',
            'Grammar and vocabulary',
            'Pronunciation and accent',
            'Cultural understanding and awareness',
            'Language immersion and practice',
            'Language proficiency exams',
            'Language teaching and tutoring',
            'Translation and interpretation',
            'Language learning apps and software',
            'Language exchange and conversation partners',
          ],
        },
        {
          name: 'Nonverbal Communication',
          image:
            'https://thumbs.dreamstime.com/b/negative-gestures-flat-vector-illustrations-set-finger-language-non-verbal-communication-people-disagree-negative-gestures-164247183.jpg',
          skills: [
            'Body language and facial expressions',
            'Gestures and postures',
            'Eye contact and gaze',
            'Touch and proximity',
            'Time and timing',
            'Appearance and attire',
            'Artifacts and objects',
            'Space and environment',
            'Intercultural communication',
            'Effective communication strategies',
          ],
        },
      ],
    },
    {
      name: 'Marketing and Advertising',
      image:
        'https://entrepreneurhandbook.co.uk/wp-content/uploads/2013/10/Different-types-of-business-promotion.jpg.webp',
      subcategories: [
        {
          name: 'Digital Marketing',
          image:
            'https://bootestech.in/wp-content/uploads/2021/01/BT-1-ST-Banner-image_Mesa-de-trabajo-11-min.png',
          skills: [
            'Search Engine Optimization (SEO)',
            'Pay-Per-Click (PPC) Advertising',
            'Social Media Marketing',
            'Email Marketing',
            'Content Marketing',
            'Video Marketing',
            'Influencer Marketing',
            'Mobile Marketing',
            'Web Analytics',
            'Digital Marketing Strategy',
          ],
        },
        {
          name: 'Traditional Marketing',
          image:
            'https://codedesign.org/storage/app/media/uploaded-files/traditional-marketing-advantage.jpg',
          skills: [
            'Print Advertising',
            'Direct Mail Marketing',
            'Outdoor Advertising',
            'Television Advertising',
            'Radio Advertising',
            'Event Marketing',
            'Promotional Marketing',
            'Public Relations',
            'Brand Management',
            'Marketing Strategy',
          ],
        },
        {
          name: 'Marketing Research',
          image:
            'https://sloanreview.mit.edu/wp-content/uploads/2018/09/GEN-Faro-Marketing-Market-Research-Big-Data-Analysis-1200x627-1200x627.jpg',
          skills: [
            'Market Segmentation',
            'Marketing Surveys',
            'Consumer Behavior Analysis',
            'Competitive Analysis',
            'Focus Groups',
            'Brand Perception Research',
            'Market Trend Analysis',
            'Marketing Analytics',
            'Data Visualization',
            'Market Research Strategy',
          ],
        },
        {
          name: 'Product Marketing',
          image:
            'https://www.clippingworld.com/wp-content/uploads/2020/02/Product-Photography-and-Photo-Editing-1.jpg',
          skills: [
            'Product Positioning',
            'Product Launch Planning',
            'Product Pricing Strategies',
            'Product Messaging and Copywriting',
            'Product Marketing Collateral',
            'Product Sales Training',
            'Product User Research',
            'Product Roadmap Planning',
            'Product Marketing Strategy',
            'Cross-functional Collaboration',
          ],
        },
        {
          name: 'Brand Marketing',
          image:
            'https://99designs-blog.imgix.net/blog/wp-content/uploads/2020/08/What_is_brand_marketing_jpg_PaibQurZ.jpg?auto=format&q=60&w=1280&h=720&fit=crop&crop=faces',
          skills: [
            'Brand Identity Development',
            'Brand Messaging',
            'Brand Guidelines',
            'Brand Awareness Campaigns',
            'Brand Activation and Events',
            'Brand Partnerships',
            'Brand Advocacy and Community Management',
            'Brand Performance Metrics',
            'Brand Marketing Strategy',
            'Brand Crisis Management',
          ],
        },
        {
          name: 'Creative Production',
          image:
            'https://www.synergostech.com/wp-content/themes/Synergos/img/Media/media.png',
          skills: [
            'Graphic Design',
            'Video Production',
            'Copywriting',
            'Art Direction',
            'Photography',
            'Animation',
            'Creative Concepting',
            'Creative Strategy',
            'Creative Project Management',
            'Creative Performance Metrics',
          ],
        },
        {
          name: 'Media Planning and Buying',
          image:
            'https://www.synergostech.com/wp-content/themes/Synergos/img/Media/media.png',
          skills: [
            'Media Planning',
            'Media Buying',
            'Media Negotiation',
            'Media Performance Analysis',
            'Media Mix Optimization',
            'Media Budget Planning',
            'Media Reporting and Analytics',
            'Media Tracking and Optimization',
            'Media Relationship Management',
            'Media Planning and Buying Strategy',
          ],
        },
        {
          name: 'E-commerce Marketing',
          image:
            'https://www.synergostech.com/wp-content/themes/Synergos/img/Media/media.png',
          skills: [
            'E-commerce SEO',
            'E-commerce PPC Advertising',
            'E-commerce Email Marketing',
            'E-commerce Content Marketing',
            'E-commerce Social Media Marketing',
            'E-commerce Conversion Rate Optimization',
            'E-commerce Affiliate Marketing',
            'E-commerce Customer Retention Strategies',
            'E-commerce Analytics and Reporting',
            'E-commerce Marketing Strategy',
          ],
        },
      ],
    },
    {
      name: 'Finance and Accounting',
      image:
        'https://www.zambianguardian.com/wp-content/uploads/2021/08/the-difference-between-accounting-and-finance.jpg',
      subcategories: [
        {
          name: 'Financial Analysis',
          image:
            'https://www.zambianguardian.com/wp-content/uploads/2021/08/the-difference-between-accounting-and-finance.jpg',
          skills: [
            'Financial Reporting',
            'Budgeting and Forecasting',
            'Financial Modeling',
            'Variance Analysis',
            'Profit and Loss Analysis',
            'Cost Benefit Analysis',
            'Cash Flow Analysis',
            'Financial Statement Analysis',
            'Investment Analysis',
            'Financial Risk Management',
          ],
        },
        {
          name: 'Corporate Accounting',
          image:
            'https://i2.wp.com/www.edupristine.com/wp-content/uploads/2018/01/Accounting.jpg?fit=300%2C300&ssl=1&resize=1280%2C720',
          skills: [
            'General Ledger Accounting',
            'Accounts Receivable and Payable Management',
            'Fixed Asset Accounting',
            'Inventory Management',
            'Financial Close Process',
            'Intercompany Accounting',
            'Revenue Recognition',
            'Tax Accounting',
            'Audit Preparation',
            'Financial Accounting Standards Compliance',
          ],
        },
        {
          name: 'Financial Planning and Strategy',
          image:
            'https://blog.qbixanalytics.com/wp-content/uploads/2022/06/healthcare_financial_planning_and_analysis_graphic.jpg',
          skills: [
            'Strategic Financial Planning',
            'Capital Budgeting',
            'Financial Forecasting',
            'Cash Management',
            'Cost Management',
            'Pricing Strategy',
            'Business Valuation',
            'Financial Due Diligence',
            'Financial Strategy Development',
            'Financial Risk Assessment',
          ],
        },
        {
          name: 'Investment Banking',
          image:
            'https://www.edubridgeindia.com/blog/storage/2022/09/future-of-investment-banking-1024x683.jpg',
          skills: [
            'Mergers and Acquisitions (M&A)',
            'Initial Public Offerings (IPOs)',
            'Debt and Equity Financing',
            'Financial Modeling',
            'Valuation Analysis',
            'Transaction Structuring',
            'Investment Due Diligence',
            'Deal Negotiation',
            'Investment Banking Regulations',
            'Investment Banking Strategy',
          ],
        },
        {
          name: 'Taxation',
          image:
            'https://www.edubridgeindia.com/blog/storage/2022/09/future-of-investment-banking-1024x683.jpg',
          skills: [
            'Income Taxation',
            'Tax Planning',
            'Sales and Use Taxation',
            'Tax Compliance',
            'International Taxation',
            'Tax Reporting',
            'Tax Audits',
            'Transfer Pricing',
            'Taxation Strategy',
            'Taxation Regulations',
          ],
        },
        {
          name: 'Financial Operations',
          image: '',
          skills: [
            'Accounts Payable and Receivable',
            'Financial Transaction Processing',
            'Financial Reporting',
            'Internal Controls',
            'Financial Systems Management',
            'Vendor Management',
            'Payroll Management',
            'Financial Data Analysis',
            'Process Improvement',
            'Financial Operations Strategy',
          ],
        },
        {
          name: 'Auditing',
          image:
            'https://www.edubridgeindia.com/blog/storage/2022/09/future-of-investment-banking-1024x683.jpg',
          skills: [
            'Audit Planning',
            'Audit Execution',
            'Risk Assessment',
            'Internal Controls Testing',
            'Audit Reporting',
            'Audit Follow-up and Corrective Action',
            'Audit Evidence Gathering',
            'Audit Documentation',
            'Audit Quality Assurance',
            'Audit Regulations',
          ],
        },
        {
          name: 'Financial Management',
          image:
            'https://dynamics.folio3.com/blog/wp-content/uploads/2021/04/Financial-Management.png',
          skills: [
            'Cash Flow Management',
            'Working Capital Management',
            'Financial Decision Making',
            'Financial Performance Analysis',
            'Cost Control',
            'Capital Structure Planning',
            'Investment Management',
            'Financial Policies and Procedures',
            'Financial Communication',
            'Financial Management Strategy',
          ],
        },
        {
          name: 'Financial Compliance',
          image:
            'https://cdn.elearningindustry.com/wp-content/uploads/2022/05/shutterstock_1395930209.jpg',
          skills: [
            'Financial Reporting Compliance',
            'Financial Standards Compliance',
            'Regulatory Compliance',
            'Ethical Compliance',
            'Internal Audit',
            'Risk Management',
            'Compliance Monitoring',
            'Compliance Training',
            'Compliance Reporting',
            'Compliance Strategy',
          ],
        },
        {
          name: 'Bookkeeping',
          image:
            'https://quickbooks.intuit.com/oidam/intuit/sbseg/en_us/Blog/Illustration/what-is-bookkeeping-hero-image-us-en.png',
          skills: [
            'Financial Data Entry',
            'Journal Entry Posting',
            'Bank Reconciliation',
            'Accounts Payable and Receivable',
            'Financial Reporting',
            'Financial Statement Preparation',
            'General Ledger Management',
            'Expense Tracking',
            'Chart of Accounts Management',
            'Bookkeeping Software',
          ],
        },
      ],
    },
    {
      name: 'Photography and Image Editing',
      image:
        'https://us.123rf.com/450wm/elenabsl/elenabsl1604/elenabsl160400014/55804367-photograph-video-making-and-photo-editing-banner-set-with-professional-equipment-laptops-and.jpg?ver=6',
      subcategories: [
        {
          name: 'Photography',
          image:
            'https://www.clippingworld.com/wp-content/uploads/2020/02/Product-Photography-and-Photo-Editing-1.jpg',
          skills: [
            'Camera Operation',
            'Composition and Framing',
            'Lighting Techniques',
            'Portrait Photography',
            'Product Photography',
            'Event Photography',
            'Landscape Photography',
            'Photo Retouching',
            'Color Correction',
            'Photo Editing Software',
          ],
        },
        {
          name: 'Image Editing',
          image:
            'https://img.freepik.com/premium-vector/professional-photographer-edit-photo-computer-er-editing-image-with-professional-software-illustration_277904-2948.jpg?w=2000',
          skills: [
            'Adobe Photoshop',
            'Adobe Lightroom',
            'GIMP',
            'Photo Retouching',
            'Color Correction',
            'Image Manipulation',
            'Digital Painting',
            'Clipping Path',
            'Masking',
            'Compositing',
          ],
        },
        {
          name: 'Video Editing',
          image:
            'https://www.clippingworld.com/wp-content/uploads/2020/02/Product-Photography-and-Photo-Editing-1.jpg',
          skills: [
            'Adobe Premiere Pro',
            'Final Cut Pro',
            'Video Color Correction',
            'Video Effects and Transitions',
            'Audio Editing',
            'Motion Graphics',
            'Video Compression',
            'Subtitling',
            'Video Encoding',
            'Video Production',
          ],
        },
      ],
    },
    {
      name: 'Project Management',
      image:
        'https://global-uploads.webflow.com/5eb6815bc8e0bd376c3cae22/635617f6b774806454f68e32_Gambar%20project%20management.png',
      subcategories: [
        {
          name: 'Project Planning',
          image:
            'https://media.istockphoto.com/id/1291339958/vector/project-management-concept-vector-illustration-business-team-working-together-with-project.jpg?s=612x612&w=0&k=20&c=N9WABnqOX_wcuUOJmIYiB3czbb1EklCgdvR8lzAda44=',
          skills: [
            'Project Scope and Requirements',
            'Project Scheduling',
            'Work Breakdown Structure',
            'Milestones and Deliverables',
            'Risk Management',
            'Resource Allocation',
            'Cost Estimation',
            'Stakeholder Management',
            'Project Management Tools',
            'Agile Methodology',
          ],
        },
        {
          name: 'Project Execution',
          image:
            'https://online.imt-pm.com/media/upload/60-pdus-project-management-pmp-renewal-strategy-for-project-execution-2.png',
          skills: [
            'Team Management',
            'Time Management',
            'Task Assignment and Tracking',
            'Project Communication',
            'Quality Assurance',
            'Change Management',
            'Project Documentation',
            'Vendor Management',
            'Project Reporting',
            'Project Management Software',
          ],
        },
        {
          name: 'Project Evaluation',
          image:
            'https://www.projectmanager.com/wp-content/uploads/2018/01/180103_Blog_Feature_Improve_Project_Evaluation-e1655155500813.jpg',
          skills: [
            'Project Performance Monitoring',
            'Project Metrics and KPIs',
            'Project Reviews and Audits',
            'Lessons Learned',
            'Continuous Improvement',
            'Project Closeout',
            'Post-Project Evaluation',
            'Project Management Certification',
            'PMP Exam Preparation',
            'Project Management Training',
          ],
        },
      ],
    },
    {
      name: 'Legal Services',
      image:
        'https://www.forbes.com/advisor/wp-content/uploads/2022/07/Legal.png',
      subcategories: [
        {
          name: 'Intellectual Property Law',
          image:
            'https://www.edology.com/media/1978/download/blogchoose-intellectual-property-law-s.png?v=1',
          skills: [
            'Trademark Registration',
            'Copyright Law',
            'Patent Law',
            'Trade Secret Law',
            'IP Licensing',
            'IP Litigation',
            'IP Valuation',
            'IP Portfolio Management',
            'Freedom to Operate Analysis',
            'Cease and Desist Letters',
          ],
        },
        {
          name: 'Contract Law',
          image:
            'https://emlaw.co.uk/wp-content/uploads/2021/03/Incorporated-By-Reference.jpg',
          skills: [
            'Contract Drafting',
            'Contract Negotiation',
            'Contract Review',
            'Breach of Contract',
            'Non-Disclosure Agreements (NDA)',
            'Employment Contracts',
            'Partnership Agreements',
            'Operating Agreements',
            'Service Agreements',
            'Sales Contracts',
          ],
        },
        {
          name: 'Corporate Law',
          image:
            'https://thumbs.dreamstime.com/b/d-isometric-flat-vector-conceptual-illustration-corporate-law-regulation-commercial-entities-224737527.jpg',
          skills: [
            'Business Formation',
            'Corporate Governance',
            'Mergers and Acquisitions',
            'Securities Law',
            'Private Equity and Venture Capital',
            'Corporate Finance',
            'Commercial Law',
            'Tax Law',
            'Bankruptcy Law',
            'International Business Transactions',
          ],
        },
        {
          name: 'Litigation',
          image: '',
          skills: [
            'Commercial Litigation',
            'Civil Litigation',
            'Employment Litigation',
            'Class Action Litigation',
            'Arbitration and Mediation',
            'Discovery',
            'Motion Practice',
            'Trial Practice',
            'Appellate Practice',
            'Alternative Dispute Resolution (ADR)',
          ],
        },
        {
          name: 'Real Estate Law',
          image:
            'https://img.freepik.com/free-vector/auction-house-abstract-concept-illustration-residential-commercial-property-auction-buy-sell-assets-online-exclusive-bid-consecutive-biddings-business-auctions_335657-1126.jpg',
          skills: [
            'Commercial Real Estate Transactions',
            'Residential Real Estate Transactions',
            'Lease Agreements',
            'Landlord-Tenant Law',
            'Real Estate Litigation',
            'Zoning and Land Use',
            'Environmental Law',
            'Eminent Domain',
            'Construction Law',
            'Real Estate Taxation',
          ],
        },
        {
          name: 'Immigration Law',
          image:
            'https://onward.justia.com/wp-content/uploads/2021/12/Marketing-Tips-Immigration-Law-Practice-Cover-1024x538.png',
          skills: [
            'Visa Applications',
            'Green Card Applications',
            'Citizenship and Naturalization',
            'Employment-Based Immigration',
            'Family-Based Immigration',
            'Deportation Defense',
            'Asylum and Refugee Law',
            'Investor Visas',
            'Humanitarian Relief',
            'Consular Processing',
          ],
        },
        {
          name: 'Banking and Finance Law',
          image: '',
          skills: [
            'Banking Regulations',
            'Securities Law',
            'Investment Banking',
            'Structured Finance',
            'Asset-Based Lending',
            'Public Finance',
            'Financial Derivatives',
            'Insurance Law',
            'Consumer Finance',
            'Project Finance',
          ],
        },
        {
          name: 'Employment Law',
          image: '',
          skills: [
            'Discrimination and Harassment Claims',
            'Wage and Hour Claims',
            'Wrongful Termination Claims',
            'Employee Benefits and Executive Compensation',
            'Employment Agreements',
            'Non-Compete Agreements',
            "Workers' Compensation",
            'Labor Law',
            'Whistleblower Claims',
            'Employment Litigation',
          ],
        },
        {
          name: 'Criminal Defense',
          image: '',
          skills: [
            'Drug Crimes',
            'Sex Crimes',
            'Violent Crimes',
            'White Collar Crimes',
            'DUI and Traffic Offenses',
          ],
        },
      ],
    },
  ],
}
