import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Landing from '@/components/Landing'
import CategoryList from '@/components/CategoryList'


export default function Home() {
  return (
    <>
      <Head>
        <title>HireLeb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Landing />
      <CategoryList />
    </>
  )
}
